### ISSUE TITLE
Pls provide an Example for varfile and template

### ISSUE THREAD

**Issue by ping2balaji** [ataccama/nomad-deploy#1]
Hi,
Can you please provide sample varfile and nomad template for the same to understand how the varfile is structured/organized against the template?
It wil be very helpful.

Thanks,
...Balaji

**Comment by iakovmarkov** [comment]
Hello,
please, take a look at commit [3e1b7ce6ca10f40159e907756f7afe603a8a7bef](https://github.com/ataccama/nomad-deploy/commit/3e1b7ce6ca10f40159e907756f7afe603a8a7bef). I think this is a good enough basic example of how the files should look like.

**Comment by iakovmarkov** [comment]
I take that as "yes" :)
